"""empty message

Revision ID: 691c2d1085be
Revises: 596ede02463c
Create Date: 2022-01-10 14:07:20.456385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691c2d1085be'
down_revision = '596ede02463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
