"""empty message

Revision ID: ee4bc74d3f8b
Revises: 81bbe62033ab
Create Date: 2022-01-09 19:25:41.756504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee4bc74d3f8b'
down_revision = '81bbe62033ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('planetName', sa.String(length=100), nullable=False))
    op.drop_column('planet', 'planet_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('planet_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('planet', 'planetName')
    # ### end Alembic commands ###
